FROM registry.access.redhat.com/ubi9-minimal@sha256:8ebe2ad8fdf3cab3e5a53c1edc69194c98209cfadab24b884f4ad9ebcf7bbbfc AS build

RUN microdnf install -y gzip tar && microdnf clean all

ADD bin/download-tools.sh .
RUN ./download-tools.sh

FROM registry.access.redhat.com/ubi9-minimal@sha256:8ebe2ad8fdf3cab3e5a53c1edc69194c98209cfadab24b884f4ad9ebcf7bbbfc

LABEL org.opencontainers.image.source="https://github.com/johankok/olm-paas-deploy" \
      org.opencontainers.image.description="Getting started with installing opr-paas on a vanilla OpenShift cluster"

COPY --from=build /usr/local/bin/* /usr/local/bin/
