FROM registry.access.redhat.com/ubi9-minimal@sha256:7fbeae18dc9476399f565e68255f602a3374ea8614ba3d14843565131a13ff93 AS build

RUN microdnf install -y gzip tar && microdnf clean all

ADD bin/download-tools.sh .
RUN ./download-tools.sh

FROM registry.access.redhat.com/ubi9-minimal@sha256:7fbeae18dc9476399f565e68255f602a3374ea8614ba3d14843565131a13ff93

LABEL org.opencontainers.image.source="https://github.com/johankok/olm-paas-deploy" \
      org.opencontainers.image.description="Getting started with installing opr-paas on a vanilla OpenShift cluster"

COPY --from=build /usr/local/bin/* /usr/local/bin/
