FROM registry.access.redhat.com/ubi9-minimal@sha256:e5161a7d7d99cf22e4f34b72e111211a399d956d9b0e8714da18e9c4c8151041 AS build

RUN microdnf install -y gzip tar && microdnf clean all

ADD bin/download-tools.sh .
RUN ./download-tools.sh

FROM registry.access.redhat.com/ubi9-minimal@sha256:e5161a7d7d99cf22e4f34b72e111211a399d956d9b0e8714da18e9c4c8151041

LABEL org.opencontainers.image.source="https://github.com/johankok/olm-paas-deploy" \
      org.opencontainers.image.description="Getting started with installing opr-paas on a vanilla OpenShift cluster"

COPY --from=build /usr/local/bin/* /usr/local/bin/
