---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: opr-paas-catalog
  namespace: openshift-marketplace
spec:
  displayName: opr-paas catalog
  image: ghcr.io/belastingdienst/opr-paas-catalog:stable
  publisher: Belastingdienst
  sourceType: grpc
