---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-generator-token
  namespace: paas-system
stringData:
  ARGOCD_GENERATOR_TOKEN: "you-should-replace-this-with-a-secure-secret-from-your-local-secret-manager"
