---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opr-paas-installation
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/johankok/olm-paas-deploy.git
    targetRevision: main
    path: installation
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
